steam:
  path: /usr/games
  executable: steamcmd
  auth:
    username: anonymous
  validate: false

lgsm:
  path: /home/kevin/lgsm
  instance_name: arma3server

arma3:
  server:
    path: /home/kevin/arma3server
  mods:
    extra_keys: []
    #  - jsrs.bikey
    collection:
      id: 3068939990
